name: 3) Deploy React app

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      AWS_PROJECT_NAME: 
        required: false
        type: string
      CONTENTFUL_CONTENT_TYPE: 
        required: false
        type: string

permissions:
  actions: read
  contents: read

jobs:
  check-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Setup was successful
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        if: ${{ github.workflow == 'deploy' }}
        run: |
          # Confirm the finalise step has successfully run
          LAST_RUN_STATUS=$(gh run list --workflow "finalise.yml" --limit 1 --json conclusion --template '{{range .}}{{.conclusion}}{{end}}')
          
          if [ "$LAST_RUN_STATUS" != "success" ]; then
            echo "Error: No successful finalise setup found (Status: $LAST_RUN_STATUS)."
            echo "Please run the 'initialise' and 'finalise' workflows first."
            exit 1
          fi

  deploy:
    needs: check-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Deploy
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_PROJECT_NAME: ${{ vars.AWS_PROJECT_NAME || inputs.AWS_PROJECT_NAME || 'BLOG' }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          VITE_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          VITE_CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
          VITE_CONTENTFUL_CONTENT_TYPE: ${{ vars.CONTENTFUL_CONTENT_TYPE || inputs.CONTENTFUL_CONTENT_TYPE || 'Blog Post' }}
        run: npm run deploy
